receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"  # Ensure OTel listens on this port
      http:
        endpoint: "0.0.0.0:4318"  # (Optional) HTTP OTLP

exporters:
  influxdb:
    endpoint: "http://influxdb:8086"  # Use the InfluxDB container name on the same Docker network
    org: "pncm"
    bucket: "bucket1"
    token: "9I3G2EyKnW4bEHwkV3Y7-dfubQD2VnXQ5x6PGMG47lQQsIAw8R0zf85-p15DOy1m-ZAIwOnODn3iwOeGuLcHqQ=="

  debug:
    verbosity: detailed

processors:
  batch:

extensions:
  health_check:
    endpoint: ":13133"
  pprof:
    endpoint: ":1777"
  zpages:
    endpoint: ":55679"

service:
  extensions: [health_check, pprof, zpages]

  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug,influxdb]
