receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"  # Removed debug: true

exporters:
  influxdb:
    endpoint: "http://influxdb:8086"
    org: "pncm"
    bucket: "bucket1"
    token: "S0NejBoaqjTEoPEYrABADGbURY7hT8gkayIKbAnJZsdMqGL7LQyPnaFMJdFlXoMDuNJsXaaSpl02Av1IYaWKDw=="
  debug:
    verbosity: detailed

processors:
  batch:
    timeout: 1s
    send_batch_size: 10

extensions:
  health_check:
    endpoint: ":13133"
  pprof:
    endpoint: ":1777"
  zpages:
    endpoint: ":55679"

service:
  telemetry:
    logs:
      level: "debug"
  extensions: [health_check, pprof, zpages]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, influxdb]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [influxdb, debug]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, influxdb]
